### PR TITLE
Replaces bitcore with bcrpc and updates dependencies to work with mod…

### PR DESCRIPTION
**Pull request by kallewoof**
…ern Node.

### CODE REVIEW

**Comment by wtogami** [comment]
With `node-v0.10.46-linux-x64` this commit no longer works.  Is it possible to make it work on both the old and latest version of node?

```
/home/oldnode/baron/lib/bcrpc.js:81
const slice = (arr, start, end) => Array.prototype.slice.call(arr, start, end)
                                 ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oldnode/baron/lib/bitcoinrpc.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by kallewoof** [comment]
Rewrote to use backwards compatible syntax. Separate commit in PR.

**Comment by wtogami** [comment]
I have no time to test this.  If you test this to work on both node 0.10  and latest I'll commit. 

It is not ideal that this code needs to support a very old version of node.  We should consider Baron to be legacy code that will not be improved, to be replaced by a rewrite that works only with modern node.

**Comment by kallewoof** [comment]
I tested on both before committing.

I'm confused though. I don't see why Baron should be considered legacy code except for the fact it is lacking an active maintainer. The code seems to work fine with the given modifications on node 0.10+.

**Comment by wtogami** [comment]
I suppose with major refactoring it could be cleaned up and made maintainable.  The code started out as spaghetti.  The database schema was not designed from the start to be ideal for the intended use case.  Both the code and the way in which it uses the database were only partially fixed to the extent of fixing race conditions and handling reorgs.  To be honest, this code is a mess and it could be done a lot better with a rewrite.

Also note your RPC library is probably missing a new RPC commands that were added to Bitcoin Core in the last two years.

**Comment by kallewoof** [comment]
That makes sense, yeah.

As for my RPC lib, no it is based on the latest version of Bitcoin Core. I deliberately removed a few deprecated commands and added all new ones. Or rather, I based my list on the Wiki not on bitcore.

**Comment by wtogami** [comment]
>  As for my RPC lib, no it is based on the latest version of Bitcoin Core. I deliberately removed a few
> deprecated commands and added all new ones. Or rather, I based my list on the Wiki not on bitcore.

Oh.   I didn't actually review it.  Is the command reference on the wiki updated?  Look at the BItcoin Core source to be sure.

**Comment by kallewoof** [comment]
This is my source: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

**Comment by wtogami** [comment]
Merged both this and your heckler PR.  Running `barontester.sh` with `node-v0.10.46-linux-x64` it appears to get through all seven tests, but I think the test result is incorrect as no double spends show up in the payment history in the browser tabs that are opened.

**Comment by wtogami** [comment]
Behaves identiclaly on node v4.5.  I am not 100% sure how it was supposed to behave.

https://github.com/slickage/baron#advanced-payment-handling
The screenshot here shows a case where it detected a double spend.  I thought one or more of the tests was supposed to detect a double spend and show it in history like this screenshot.

In any case, it isn't important to fix Baron in this regard if your rewrite gets this behavior correct.

**Comment by kallewoof** [comment]
It's very easy to verify -- just grab the old github repo and test it on node 0.10 and compare. I don't think I saw any double spends but I did see a reorg. I still see that one with the latest code though.

**Pull request merged**
